// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: migrator/migrator.proto

package migrator

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос для создания миграции
type CreateMigrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                           // Название миграции
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                             // Описание миграции
	Script         string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`                                       // Текст скрипта миграции
	RollbackScript string                 `protobuf:"bytes,4,opt,name=rollback_script,json=rollbackScript,proto3" json:"rollback_script,omitempty"` // Текст скрипта отката миграции
	UserId         int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // Идентификатор пользователя, создающего миграцию
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMigrationRequest) Reset() {
	*x = CreateMigrationRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationRequest) ProtoMessage() {}

func (x *CreateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationRequest.ProtoReflect.Descriptor instead.
func (*CreateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMigrationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMigrationRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *CreateMigrationRequest) GetRollbackScript() string {
	if x != nil {
		return x.RollbackScript
	}
	return ""
}

func (x *CreateMigrationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на запрос для создания миграции
type CreateMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор созданной миграции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMigrationResponse) Reset() {
	*x = CreateMigrationResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationResponse) ProtoMessage() {}

func (x *CreateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationResponse.ProtoReflect.Descriptor instead.
func (*CreateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMigrationResponse) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

// Запрос для применения миграций
type ApplyMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationIds  []int64                `protobuf:"varint,1,rep,packed,name=migration_ids,json=migrationIds,proto3" json:"migration_ids,omitempty"` // Уникальные идентификаторы миграций в соответствии с порядком применения
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          // Идентификатор пользователя, применяющего миграцию
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMigrationRequest) Reset() {
	*x = ApplyMigrationRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMigrationRequest) ProtoMessage() {}

func (x *ApplyMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMigrationRequest.ProtoReflect.Descriptor instead.
func (*ApplyMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyMigrationRequest) GetMigrationIds() []int64 {
	if x != nil {
		return x.MigrationIds
	}
	return nil
}

func (x *ApplyMigrationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на запрос для применения миграций
type ApplyMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppliedAt     string                 `protobuf:"bytes,1,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"` // Дата и время применения миграции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMigrationResponse) Reset() {
	*x = ApplyMigrationResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMigrationResponse) ProtoMessage() {}

func (x *ApplyMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMigrationResponse.ProtoReflect.Descriptor instead.
func (*ApplyMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyMigrationResponse) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

// Запрос для отката миграции
type RollbackMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор миграции
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // Идентификатор пользователя, выполняющего откат
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackMigrationRequest) Reset() {
	*x = RollbackMigrationRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationRequest) ProtoMessage() {}

func (x *RollbackMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationRequest.ProtoReflect.Descriptor instead.
func (*RollbackMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackMigrationRequest) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

func (x *RollbackMigrationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на запрос для отката миграции
type RollbackMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolledBackAt  string                 `protobuf:"bytes,1,opt,name=rolled_back_at,json=rolledBackAt,proto3" json:"rolled_back_at,omitempty"` // Дата и время отката миграции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackMigrationResponse) Reset() {
	*x = RollbackMigrationResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationResponse) ProtoMessage() {}

func (x *RollbackMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationResponse.ProtoReflect.Descriptor instead.
func (*RollbackMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackMigrationResponse) GetRolledBackAt() string {
	if x != nil {
		return x.RolledBackAt
	}
	return ""
}

// Запрос для получения списка миграций
type ListMigrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // Фильтр по статусу (например, "pending", "applied", "rolled_back")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMigrationsRequest) Reset() {
	*x = ListMigrationsRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsRequest) ProtoMessage() {}

func (x *ListMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsRequest.ProtoReflect.Descriptor instead.
func (*ListMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{6}
}

func (x *ListMigrationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Информация о миграции
type MigrationInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                   // Уникальный идентификатор миграции
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                // Название миграции
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                  // Описание миграции
	Script          string                 `protobuf:"bytes,4,opt,name=script,proto3" json:"script,omitempty"`                                            // Текст скрипта миграции
	RollbackScript  string                 `protobuf:"bytes,5,opt,name=rollback_script,json=rollbackScript,proto3" json:"rollback_script,omitempty"`      // Текст скрипта отката миграции
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                            // Текущий статус миграции
	CreatedBy       int64                  `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`                    // Идентификатор пользователя, применившего миграцию
	StatusUpdatedAt string                 `protobuf:"bytes,8,opt,name=status_updated_at,json=statusUpdatedAt,proto3" json:"status_updated_at,omitempty"` // Дата и время обновления статуса миграции
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MigrationInfo) Reset() {
	*x = MigrationInfo{}
	mi := &file_migrator_migrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationInfo) ProtoMessage() {}

func (x *MigrationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationInfo.ProtoReflect.Descriptor instead.
func (*MigrationInfo) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{7}
}

func (x *MigrationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MigrationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrationInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MigrationInfo) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *MigrationInfo) GetRollbackScript() string {
	if x != nil {
		return x.RollbackScript
	}
	return ""
}

func (x *MigrationInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MigrationInfo) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *MigrationInfo) GetStatusUpdatedAt() string {
	if x != nil {
		return x.StatusUpdatedAt
	}
	return ""
}

// Ответ на запрос для получения списка миграций
type ListMigrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migrations    []*MigrationInfo       `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"` // Список миграций
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMigrationsResponse) Reset() {
	*x = ListMigrationsResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsResponse) ProtoMessage() {}

func (x *ListMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsResponse.ProtoReflect.Descriptor instead.
func (*ListMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{8}
}

func (x *ListMigrationsResponse) GetMigrations() []*MigrationInfo {
	if x != nil {
		return x.Migrations
	}
	return nil
}

// Запрос для получения миграции
type GetMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор миграции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationRequest) Reset() {
	*x = GetMigrationRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationRequest) ProtoMessage() {}

func (x *GetMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{9}
}

func (x *GetMigrationRequest) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

// Ответ на запрос для получения миграции
type GetMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *MigrationInfo         `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"` // Миграция
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationResponse) Reset() {
	*x = GetMigrationResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationResponse) ProtoMessage() {}

func (x *GetMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{10}
}

func (x *GetMigrationResponse) GetMigration() *MigrationInfo {
	if x != nil {
		return x.Migration
	}
	return nil
}

var File_migrator_migrator_proto protoreflect.FileDescriptor

const file_migrator_migrator_proto_rawDesc = "" +
	"\n" +
	"\x17migrator/migrator.proto\x12\tmigration\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa8\x01\n" +
	"\x16CreateMigrationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12'\n" +
	"\x0frollback_script\x18\x04 \x01(\tR\x0erollbackScript\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\"<\n" +
	"\x17CreateMigrationResponse\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\"U\n" +
	"\x15ApplyMigrationRequest\x12#\n" +
	"\rmigration_ids\x18\x01 \x03(\x03R\fmigrationIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"7\n" +
	"\x16ApplyMigrationResponse\x12\x1d\n" +
	"\n" +
	"applied_at\x18\x01 \x01(\tR\tappliedAt\"V\n" +
	"\x18RollbackMigrationRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"A\n" +
	"\x19RollbackMigrationResponse\x12$\n" +
	"\x0erolled_back_at\x18\x01 \x01(\tR\frolledBackAt\"/\n" +
	"\x15ListMigrationsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xf9\x01\n" +
	"\rMigrationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06script\x18\x04 \x01(\tR\x06script\x12'\n" +
	"\x0frollback_script\x18\x05 \x01(\tR\x0erollbackScript\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\x03R\tcreatedBy\x12*\n" +
	"\x11status_updated_at\x18\b \x01(\tR\x0fstatusUpdatedAt\"R\n" +
	"\x16ListMigrationsResponse\x128\n" +
	"\n" +
	"migrations\x18\x01 \x03(\v2\x18.migration.MigrationInfoR\n" +
	"migrations\"8\n" +
	"\x13GetMigrationRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\"N\n" +
	"\x14GetMigrationResponse\x126\n" +
	"\tmigration\x18\x01 \x01(\v2\x18.migration.MigrationInfoR\tmigration2\xfa\x04\n" +
	"\x10MigrationService\x12s\n" +
	"\x0fCreateMigration\x12!.migration.CreateMigrationRequest\x1a\".migration.CreateMigrationResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/migrations\x12v\n" +
	"\x0eApplyMigration\x12 .migration.ApplyMigrationRequest\x1a!.migration.ApplyMigrationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/migrations/apply\x12\x91\x01\n" +
	"\x11RollbackMigration\x12#.migration.RollbackMigrationRequest\x1a$.migration.RollbackMigrationResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/migrations/{migration_id}/rollback\x12m\n" +
	"\x0eListMigrations\x12 .migration.ListMigrationsRequest\x1a!.migration.ListMigrationsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/migrations\x12v\n" +
	"\fGetMigration\x12\x1e.migration.GetMigrationRequest\x1a\x1f.migration.GetMigrationResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/migrations/{migration_id}B*\x92A\x10\x1a\x0elocalhost:8080Z\x15migrator/api/migratorb\x06proto3"

var (
	file_migrator_migrator_proto_rawDescOnce sync.Once
	file_migrator_migrator_proto_rawDescData []byte
)

func file_migrator_migrator_proto_rawDescGZIP() []byte {
	file_migrator_migrator_proto_rawDescOnce.Do(func() {
		file_migrator_migrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migrator_migrator_proto_rawDesc), len(file_migrator_migrator_proto_rawDesc)))
	})
	return file_migrator_migrator_proto_rawDescData
}

var file_migrator_migrator_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_migrator_migrator_proto_goTypes = []any{
	(*CreateMigrationRequest)(nil),    // 0: migration.CreateMigrationRequest
	(*CreateMigrationResponse)(nil),   // 1: migration.CreateMigrationResponse
	(*ApplyMigrationRequest)(nil),     // 2: migration.ApplyMigrationRequest
	(*ApplyMigrationResponse)(nil),    // 3: migration.ApplyMigrationResponse
	(*RollbackMigrationRequest)(nil),  // 4: migration.RollbackMigrationRequest
	(*RollbackMigrationResponse)(nil), // 5: migration.RollbackMigrationResponse
	(*ListMigrationsRequest)(nil),     // 6: migration.ListMigrationsRequest
	(*MigrationInfo)(nil),             // 7: migration.MigrationInfo
	(*ListMigrationsResponse)(nil),    // 8: migration.ListMigrationsResponse
	(*GetMigrationRequest)(nil),       // 9: migration.GetMigrationRequest
	(*GetMigrationResponse)(nil),      // 10: migration.GetMigrationResponse
}
var file_migrator_migrator_proto_depIdxs = []int32{
	7,  // 0: migration.ListMigrationsResponse.migrations:type_name -> migration.MigrationInfo
	7,  // 1: migration.GetMigrationResponse.migration:type_name -> migration.MigrationInfo
	0,  // 2: migration.MigrationService.CreateMigration:input_type -> migration.CreateMigrationRequest
	2,  // 3: migration.MigrationService.ApplyMigration:input_type -> migration.ApplyMigrationRequest
	4,  // 4: migration.MigrationService.RollbackMigration:input_type -> migration.RollbackMigrationRequest
	6,  // 5: migration.MigrationService.ListMigrations:input_type -> migration.ListMigrationsRequest
	9,  // 6: migration.MigrationService.GetMigration:input_type -> migration.GetMigrationRequest
	1,  // 7: migration.MigrationService.CreateMigration:output_type -> migration.CreateMigrationResponse
	3,  // 8: migration.MigrationService.ApplyMigration:output_type -> migration.ApplyMigrationResponse
	5,  // 9: migration.MigrationService.RollbackMigration:output_type -> migration.RollbackMigrationResponse
	8,  // 10: migration.MigrationService.ListMigrations:output_type -> migration.ListMigrationsResponse
	10, // 11: migration.MigrationService.GetMigration:output_type -> migration.GetMigrationResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_migrator_migrator_proto_init() }
func file_migrator_migrator_proto_init() {
	if File_migrator_migrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migrator_migrator_proto_rawDesc), len(file_migrator_migrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migrator_migrator_proto_goTypes,
		DependencyIndexes: file_migrator_migrator_proto_depIdxs,
		MessageInfos:      file_migrator_migrator_proto_msgTypes,
	}.Build()
	File_migrator_migrator_proto = out.File
	file_migrator_migrator_proto_goTypes = nil
	file_migrator_migrator_proto_depIdxs = nil
}
