// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: migrator/migrator.proto

package migrator

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщения для создания миграции
type CreateMigrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                           // Название миграции
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                             // Описание миграции
	Script         string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`                                       // Текст скрипта миграции
	RollbackScript string                 `protobuf:"bytes,4,opt,name=rollback_script,json=rollbackScript,proto3" json:"rollback_script,omitempty"` // Текст скрипта отката миграции
	UserId         int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // Идентификатор пользователя, создающего миграцию
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMigrationRequest) Reset() {
	*x = CreateMigrationRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationRequest) ProtoMessage() {}

func (x *CreateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationRequest.ProtoReflect.Descriptor instead.
func (*CreateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMigrationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMigrationRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *CreateMigrationRequest) GetRollbackScript() string {
	if x != nil {
		return x.RollbackScript
	}
	return ""
}

func (x *CreateMigrationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор созданной миграции
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                               // Статус миграции после создания (например, "pending")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMigrationResponse) Reset() {
	*x = CreateMigrationResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationResponse) ProtoMessage() {}

func (x *CreateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationResponse.ProtoReflect.Descriptor instead.
func (*CreateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMigrationResponse) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

func (x *CreateMigrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Сообщения для применения миграции
type ApplyMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор миграции
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // Идентификатор пользователя, применяющего миграцию
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMigrationRequest) Reset() {
	*x = ApplyMigrationRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMigrationRequest) ProtoMessage() {}

func (x *ApplyMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMigrationRequest.ProtoReflect.Descriptor instead.
func (*ApplyMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyMigrationRequest) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

func (x *ApplyMigrationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ApplyMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор миграции
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                               // Статус миграции после применения (например, "applied")
	AppliedAt     string                 `protobuf:"bytes,3,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`        // Дата и время применения миграции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMigrationResponse) Reset() {
	*x = ApplyMigrationResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMigrationResponse) ProtoMessage() {}

func (x *ApplyMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMigrationResponse.ProtoReflect.Descriptor instead.
func (*ApplyMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyMigrationResponse) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

func (x *ApplyMigrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApplyMigrationResponse) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

// Сообщения для отката миграции
type RollbackMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор миграции
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // Идентификатор пользователя, выполняющего откат
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackMigrationRequest) Reset() {
	*x = RollbackMigrationRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationRequest) ProtoMessage() {}

func (x *RollbackMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationRequest.ProtoReflect.Descriptor instead.
func (*RollbackMigrationRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackMigrationRequest) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

func (x *RollbackMigrationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RollbackMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`     // Уникальный идентификатор миграции
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                   // Статус миграции после отката (например, "rolled_back")
	RolledBackAt  string                 `protobuf:"bytes,3,opt,name=rolled_back_at,json=rolledBackAt,proto3" json:"rolled_back_at,omitempty"` // Дата и время отката миграции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackMigrationResponse) Reset() {
	*x = RollbackMigrationResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationResponse) ProtoMessage() {}

func (x *RollbackMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationResponse.ProtoReflect.Descriptor instead.
func (*RollbackMigrationResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackMigrationResponse) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

func (x *RollbackMigrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RollbackMigrationResponse) GetRolledBackAt() string {
	if x != nil {
		return x.RolledBackAt
	}
	return ""
}

// Сообщения для получения списка миграций
type ListMigrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // Фильтр по статусу (например, "pending", "applied", "rolled_back")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMigrationsRequest) Reset() {
	*x = ListMigrationsRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsRequest) ProtoMessage() {}

func (x *ListMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsRequest.ProtoReflect.Descriptor instead.
func (*ListMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{6}
}

func (x *ListMigrationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MigrationInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // Уникальный идентификатор миграции
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                           // Название миграции
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                             // Описание миграции
	ScriptPath     string                 `protobuf:"bytes,4,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"`             // Путь к файлу скрипта миграции
	RollbackScript string                 `protobuf:"bytes,5,opt,name=rollback_script,json=rollbackScript,proto3" json:"rollback_script,omitempty"` // Путь к файлу скрипта отката миграции
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                       // Текущий статус миграции
	AppliedBy      int64                  `protobuf:"varint,7,opt,name=applied_by,json=appliedBy,proto3" json:"applied_by,omitempty"`               // Идентификатор пользователя, применившего миграцию
	AppliedAt      string                 `protobuf:"bytes,8,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`                // Дата и время применения миграции
	RolledBackBy   int64                  `protobuf:"varint,9,opt,name=rolled_back_by,json=rolledBackBy,proto3" json:"rolled_back_by,omitempty"`    // Идентификатор пользователя, выполнившего откат
	RolledBackAt   string                 `protobuf:"bytes,10,opt,name=rolled_back_at,json=rolledBackAt,proto3" json:"rolled_back_at,omitempty"`    // Дата и время отката миграции
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MigrationInfo) Reset() {
	*x = MigrationInfo{}
	mi := &file_migrator_migrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationInfo) ProtoMessage() {}

func (x *MigrationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationInfo.ProtoReflect.Descriptor instead.
func (*MigrationInfo) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{7}
}

func (x *MigrationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MigrationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrationInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MigrationInfo) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *MigrationInfo) GetRollbackScript() string {
	if x != nil {
		return x.RollbackScript
	}
	return ""
}

func (x *MigrationInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MigrationInfo) GetAppliedBy() int64 {
	if x != nil {
		return x.AppliedBy
	}
	return 0
}

func (x *MigrationInfo) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

func (x *MigrationInfo) GetRolledBackBy() int64 {
	if x != nil {
		return x.RolledBackBy
	}
	return 0
}

func (x *MigrationInfo) GetRolledBackAt() string {
	if x != nil {
		return x.RolledBackAt
	}
	return ""
}

type ListMigrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migrations    []*MigrationInfo       `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"` // Список миграций
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMigrationsResponse) Reset() {
	*x = ListMigrationsResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsResponse) ProtoMessage() {}

func (x *ListMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsResponse.ProtoReflect.Descriptor instead.
func (*ListMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{8}
}

func (x *ListMigrationsResponse) GetMigrations() []*MigrationInfo {
	if x != nil {
		return x.Migrations
	}
	return nil
}

// Сообщения для получения статуса миграции
type GetMigrationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор миграции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationStatusRequest) Reset() {
	*x = GetMigrationStatusRequest{}
	mi := &file_migrator_migrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationStatusRequest) ProtoMessage() {}

func (x *GetMigrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{9}
}

func (x *GetMigrationStatusRequest) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

type GetMigrationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   int64                  `protobuf:"varint,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Уникальный идентификатор миграции
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                               // Текущий статус миграции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationStatusResponse) Reset() {
	*x = GetMigrationStatusResponse{}
	mi := &file_migrator_migrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationStatusResponse) ProtoMessage() {}

func (x *GetMigrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrator_migrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_migrator_migrator_proto_rawDescGZIP(), []int{10}
}

func (x *GetMigrationStatusResponse) GetMigrationId() int64 {
	if x != nil {
		return x.MigrationId
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_migrator_migrator_proto protoreflect.FileDescriptor

const file_migrator_migrator_proto_rawDesc = "" +
	"\n" +
	"\x17migrator/migrator.proto\x12\tmigration\x1a\x1cgoogle/api/annotations.proto\"\xa8\x01\n" +
	"\x16CreateMigrationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12'\n" +
	"\x0frollback_script\x18\x04 \x01(\tR\x0erollbackScript\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\"T\n" +
	"\x17CreateMigrationResponse\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"S\n" +
	"\x15ApplyMigrationRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"r\n" +
	"\x16ApplyMigrationResponse\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"applied_at\x18\x03 \x01(\tR\tappliedAt\"V\n" +
	"\x18RollbackMigrationRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"|\n" +
	"\x19RollbackMigrationResponse\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12$\n" +
	"\x0erolled_back_at\x18\x03 \x01(\tR\frolledBackAt\"/\n" +
	"\x15ListMigrationsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc1\x02\n" +
	"\rMigrationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vscript_path\x18\x04 \x01(\tR\n" +
	"scriptPath\x12'\n" +
	"\x0frollback_script\x18\x05 \x01(\tR\x0erollbackScript\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"applied_by\x18\a \x01(\x03R\tappliedBy\x12\x1d\n" +
	"\n" +
	"applied_at\x18\b \x01(\tR\tappliedAt\x12$\n" +
	"\x0erolled_back_by\x18\t \x01(\x03R\frolledBackBy\x12$\n" +
	"\x0erolled_back_at\x18\n" +
	" \x01(\tR\frolledBackAt\"R\n" +
	"\x16ListMigrationsResponse\x128\n" +
	"\n" +
	"migrations\x18\x01 \x03(\v2\x18.migration.MigrationInfoR\n" +
	"migrations\">\n" +
	"\x19GetMigrationStatusRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\"W\n" +
	"\x1aGetMigrationStatusResponse\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\x03R\vmigrationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xa4\x05\n" +
	"\x10MigrationService\x12s\n" +
	"\x0fCreateMigration\x12!.migration.CreateMigrationRequest\x1a\".migration.CreateMigrationResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/migrations\x12\x85\x01\n" +
	"\x0eApplyMigration\x12 .migration.ApplyMigrationRequest\x1a!.migration.ApplyMigrationResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/migrations/{migration_id}/apply\x12\x91\x01\n" +
	"\x11RollbackMigration\x12#.migration.RollbackMigrationRequest\x1a$.migration.RollbackMigrationResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/migrations/{migration_id}/rollback\x12m\n" +
	"\x0eListMigrations\x12 .migration.ListMigrationsRequest\x1a!.migration.ListMigrationsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/migrations\x12\x8f\x01\n" +
	"\x12GetMigrationStatus\x12$.migration.GetMigrationStatusRequest\x1a%.migration.GetMigrationStatusResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/migrations/{migration_id}/statusB\x17Z\x15migrator/api/migratorb\x06proto3"

var (
	file_migrator_migrator_proto_rawDescOnce sync.Once
	file_migrator_migrator_proto_rawDescData []byte
)

func file_migrator_migrator_proto_rawDescGZIP() []byte {
	file_migrator_migrator_proto_rawDescOnce.Do(func() {
		file_migrator_migrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migrator_migrator_proto_rawDesc), len(file_migrator_migrator_proto_rawDesc)))
	})
	return file_migrator_migrator_proto_rawDescData
}

var file_migrator_migrator_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_migrator_migrator_proto_goTypes = []any{
	(*CreateMigrationRequest)(nil),     // 0: migration.CreateMigrationRequest
	(*CreateMigrationResponse)(nil),    // 1: migration.CreateMigrationResponse
	(*ApplyMigrationRequest)(nil),      // 2: migration.ApplyMigrationRequest
	(*ApplyMigrationResponse)(nil),     // 3: migration.ApplyMigrationResponse
	(*RollbackMigrationRequest)(nil),   // 4: migration.RollbackMigrationRequest
	(*RollbackMigrationResponse)(nil),  // 5: migration.RollbackMigrationResponse
	(*ListMigrationsRequest)(nil),      // 6: migration.ListMigrationsRequest
	(*MigrationInfo)(nil),              // 7: migration.MigrationInfo
	(*ListMigrationsResponse)(nil),     // 8: migration.ListMigrationsResponse
	(*GetMigrationStatusRequest)(nil),  // 9: migration.GetMigrationStatusRequest
	(*GetMigrationStatusResponse)(nil), // 10: migration.GetMigrationStatusResponse
}
var file_migrator_migrator_proto_depIdxs = []int32{
	7,  // 0: migration.ListMigrationsResponse.migrations:type_name -> migration.MigrationInfo
	0,  // 1: migration.MigrationService.CreateMigration:input_type -> migration.CreateMigrationRequest
	2,  // 2: migration.MigrationService.ApplyMigration:input_type -> migration.ApplyMigrationRequest
	4,  // 3: migration.MigrationService.RollbackMigration:input_type -> migration.RollbackMigrationRequest
	6,  // 4: migration.MigrationService.ListMigrations:input_type -> migration.ListMigrationsRequest
	9,  // 5: migration.MigrationService.GetMigrationStatus:input_type -> migration.GetMigrationStatusRequest
	1,  // 6: migration.MigrationService.CreateMigration:output_type -> migration.CreateMigrationResponse
	3,  // 7: migration.MigrationService.ApplyMigration:output_type -> migration.ApplyMigrationResponse
	5,  // 8: migration.MigrationService.RollbackMigration:output_type -> migration.RollbackMigrationResponse
	8,  // 9: migration.MigrationService.ListMigrations:output_type -> migration.ListMigrationsResponse
	10, // 10: migration.MigrationService.GetMigrationStatus:output_type -> migration.GetMigrationStatusResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_migrator_migrator_proto_init() }
func file_migrator_migrator_proto_init() {
	if File_migrator_migrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migrator_migrator_proto_rawDesc), len(file_migrator_migrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migrator_migrator_proto_goTypes,
		DependencyIndexes: file_migrator_migrator_proto_depIdxs,
		MessageInfos:      file_migrator_migrator_proto_msgTypes,
	}.Build()
	File_migrator_migrator_proto = out.File
	file_migrator_migrator_proto_goTypes = nil
	file_migrator_migrator_proto_depIdxs = nil
}
